# Logistic Regression
by Andrew E. Davidson

This notebook is an introduction to TensorFlow. To illustrate how basic TensorFlow works we are going to implement binary classifier using Logistic Regression. Logistic Regression can be thought of as neural network with a single neuron. Its simple enough that we can implement the algorithm manually. With the interest of learning how tensor flow works we are not going to take advantage of automatic differentiation or tensoflow optimizers. Using auto-diff and optimizers would dramatically reduce the amount of code required.

Note: [train.ipynb](train.ipynb) is a version of logistic regression using Keras. Its a fraction of the code a TensorFlow only solution requires.

<span style="color:red">There are couple of place where I used numpy reshape or to scale the feature matrix. This should be changed to use TensorFlow. Using numpy will work if you are using a single machine. Tensorflow will scale across a cluster.</span>
    
Supervised learning applications implemented with TensorFlow typically have the following structure
1. load some data

2. construct our 'computation graph'
    1. Initialize our input variables, model parameters, and place holders
    1. Forward Propagation
        * create graph that makes predictions give our features and model
    2. Calculate Cost
        * create graph to measure how well our preidiction match our lables
    3. Back Propagation
        * calculate the graidents. (i.e. the partical derivatites of our cost function with respect to the partameters our model learns
    4. use the gradients to update the learned parameters of our model
3. Train our model
    1. Use an optimizer or gradient decent with mini-batches
    2. save check points and final model
    3. save performance statistics. 
4. evaluate our model's performance on the training data set
5. evaluate our model's performance on the test data set
6. tune hyper parmeters 
7. goto to 1.

### TODO
- save check point and model
- run on large data set
- does model generalize?

In [1]:
import logRegTestFunc as lrTest
import numpy as np
import os
import pandas as pd
import tensorflow as tf
import keras
from scipy import stats

# fix random seed for reproducibility
np.random.seed(42)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


# 1) Load RNA Seq data

In [2]:
from keras.utils.io_utils import HDF5Matrix
import h5py

In [3]:
def full_data_set(input_file):
    print("Training on full dataset")
    X_train = HDF5Matrix(input_file, "X_train")
    X_test = HDF5Matrix(input_file, "X_test")
    y_train = HDF5Matrix(input_file, "y_train")
    y_test = HDF5Matrix(input_file, "y_test")
    
    return [X_train, X_test, y_train, y_test]

def small_data_set(input_file):
    print("Training on partial dataset")
    X_train = HDF5Matrix(input_file, "X_train", start=0, end=1000)
    X_test = HDF5Matrix(input_file, "X_test", start=0, end=200)
    y_train = HDF5Matrix(input_file, "y_train", start=0, end=1000)
    y_test = HDF5Matrix(input_file, "y_test", start=0, end=200)
    
    return [X_train, X_test, y_train, y_test]

In [4]:
%%time

input_file = "data/tumor_normal.h5"

with h5py.File(input_file, "r") as f:
    print("Datasets:", list(f.keys()))
    
DEBUG = False 
if DEBUG:
    # this data set is simple enough we can do the math on paper
    print("Training on trival (debug) dataset")
    X_train = np.array([
                        [ 1.,  2.],
                        [ 3.,  4.],
                        [ 5.,  6.],
                        [ 7.,  8.],
                        [ 9., 10.],
                        [11., 12.],
                        [13., 14]
                            ])
    
    # y_train must be a rank 2 array
    # i.e. we want transpose of y_train to be a column vector not an array
    y_train = np.array( [[0., 0., 0., 1., 1., 1., 1.]] )
    X_test = X_train * 10
    y_test = y_train
    
    epochs = 5000
    batch_size = 3
    log_frequence = 100
    
else:
    #X_train, X_test, y_train, y_test = full_data_set(input_file)
    X_train, X_test, y_train, y_test = small_data_set(input_file)
    
    n,m = np.transpose(X_train).shape
    m_test = y_test.shape[0]
    
    # reshape array into a column vector
    y_train = np.reshape(y_train, (1,m))
    y_test = np.reshape(y_test, (1,m_test))

    epochs=100
    batch_size=128
    log_frequence = epochs / 5 #1 if DEBUG else 20 

    
# transpose, each column should be a separate sample
X_train = np.transpose( X_train )
n,m = X_train.shape

X_test = np.transpose( X_test )
assert X_test.shape == (n, X_test.shape[1]), "X_test shape failed"

print( "X_train.shape: ", X_train.shape)
print( "X_test.shape: ", X_test.shape)

print("y_train.shape:", y_train.shape)
assert y_train.shape == (1,m), "y_train shape failed"

print("y_test.shape:", y_train.shape)
assert y_test.shape == (1, X_test.shape[1])

print( "epochs: ", epochs )
print( "batch_size: ", batch_size )

print( "n: num features: ", n)
expectedNumFeatures = 2 if DEBUG else 60498

msg = "expected:" + str(expectedNumFeatures) + " actual:" + str(n)
assert (n == expectedNumFeatures), msg

print( "m: num training samples: ", m)

Datasets: ['X_test', 'X_train', 'class_labels', 'classes_test', 'classes_train', 'features', 'genes', 'labels', 'y_test', 'y_train']
Training on partial dataset
X_train.shape:  (60498, 1000)
X_test.shape:  (60498, 200)
y_train.shape: (1, 1000)
y_test.shape: (1, 1000)
epochs:  100
batch_size:  128
n: num features:  60498
m: num training samples:  1000
CPU times: user 1.28 s, sys: 1.1 s, total: 2.38 s
Wall time: 2.38 s


## Explore RNA Seq data
Given the way the sigmoid function works, the raw data will spend a lot of time learning using gradients near zero. We can speed up learning by normalizing the data.

In [5]:
def normalizeData(X):
    """scales data such that mean=0 and standard deviation=1"""
    n,m = X.shape
    
    # axis=1 cause calculation to run across rows
    means = np.mean(X, axis=1).reshape(n, 1)
    std = np.std(X, axis=1).reshape(n, 1)
    #mean, std = tf.nn.moments(X, axes=[1])
    
    centered = X - means
    return (centered / std)

if DEBUG:
    testND = np.arange(start=1., stop=13.).reshape(4,3)
    result = normalizeData(testND)

    assert np.array_equal( np.mean(result, axis=1), 
                          np.array([0.,0.,0.,0.]) )
    assert sum(np.isclose( np.var(result, axis=1), 
                          np.array([1.,1.,1.,1.]) ), 4)

if not DEBUG:
    # explore some of the X_train data
    # do we need to normalize?
    print("******** Explore RNA Seq data *******")
    print("Raw Data, rows are features")
    print("\nX_train[0:2,0:8]\n", X_train[0:2,0:8])
    print("\nX_train[100:102,0:8]\n", X_train[100:102,0:8])
    
    print("\ny_train[0, 0:8]\n", y_train[0, 0:8])

    print("\nSummary stats for two genes")
    s = stats.describe(X_train[0,:])
    print("\nX_train[0,:]\n minmax:{} mean:{} variance:{}"
              .format(s.minmax, s.mean, s.variance) )
    
    s = stats.describe(X_train[99,:])
    print("\nX_train[99,:]\n minmax:{} mean:{} variance:{}"
              .format(s.minmax, s.mean, s.variance) )  
    
    print("\n********** normalizing data ********")
    X_train = normalizeData( X_train )
    X_test = normalizeData( X_train )

******** Explore RNA Seq data *******
Raw Data, rows are features

X_train[0:2,0:8]
 [[-4.035  -9.9658 -9.9658 -9.9658 -9.9658 -5.0116 -9.9658 -2.4659]
 [-9.9658 -9.9658 -9.9658 -9.9658 -9.9658 -9.9658 -9.9658 -9.9658]]

X_train[100:102,0:8]
 [[-9.9658 -9.9658 -9.9658 -9.9658 -9.9658 -9.9658 -9.9658 -9.9658]
 [-0.3201 -3.3076  1.6875  2.6579 -2.6349  2.5338  0.03    6.6964]]

y_train[0, 0:8]
 [0 0 1 1 0 1 1 0]

Summary stats for two genes

X_train[0,:]
 minmax:(-9.9658, 2.1894) mean:-6.864265441894531 variance:14.995550155639648

X_train[99,:]
 minmax:(-9.9658, 1.2271) mean:-5.610025405883789 variance:16.54981803894043

********** normalizing data ********


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


# 2) Construction Computation Graph 
If you want to use TensorBoard to visualize your graph make sure you give all ops a name, and group releated ops using "name scopes"

In [6]:
# clear out any nodes from previous runs
tf.reset_default_graph()

## Forward Propagation
Create a graph that makes predictions given our features and model

### Init place holders and variables

In [7]:
# We use tf.name_scope() to group tensor operations in the graph image 
# created by TensorBoard. Use either the "name" argument or tf.identity to 
# lable nodes in the in the TensorBoard Image

with tf.name_scope("input_data"):
    # shape( None ) means the deminsion is not know. This is because the 
    # last min batch may have fewer samples. i.e. m / batch_size  may have 
    # a remainder

    # X is our feature matrix
    X = tf.placeholder( tf.float64, shape=(n, None), name="X")
    print("X.shape: ", X.shape)

    # y is our lable vector
    y = tf.placeholder( tf.float64, shape=(1, None), name="y")
    print("y.shape:", y.shape)

# initialize our model parameters.
# w is our models weight vector
# b is the y intercept for a linear model
with tf.name_scope("model_parameters"):
    if DEBUG:
        # ones() makes it easy to write unit tests
        w = tf.Variable( np.ones(( n, 1 )), name="w")
        b = tf.Variable( 1.0, name="b", dtype=tf.float64)
    else:
        # usally machine learning algorithms init values using a uniform
        # random distribution. Logistic regression typically uses zero.
        # This should make learning faster. Has to do with the 
        # shape of the 
        
        # sigmoid function
        w = tf.Variable( np.zeros(( n, 1 )), name="w")
        b = tf.Variable( 0., name="b", dtype=tf.float64)
    
print("w.shape: ", w.shape)
print("tf.transpose(w).shape: ", tf.transpose(w).shape)

print("b.dtype: ", b.dtype)

X.shape:  (60498, ?)
y.shape: (1, ?)
w.shape:  (60498, 1)
tf.transpose(w).shape:  (1, 60498)
b.dtype:  <dtype: 'float64_ref'>


Compute z: the input to Sigmoid()
$$ 
z\: =\: { W }^{ t }X\: +\: b \tag{1}
$$

### prediction
Compute z: the input to Sigmoid()
$$ 
z\: =\: { W }^{ t }X\: +\: b \tag{1}
$$

Compute the "neuron activation"
$$ 
a \: = \:  \sigma (z)\: =\: 1\, /\, (1\: +\: { e }^{ -z }) \tag{2}
$$

In [8]:
with tf.name_scope("Predict"):
    # define forward propagation
    # z has shape [1,m]
    z = tf.matmul(tf.transpose(w), X) + b
    tf.identity(z, "z")

    # sigmoid has shape [1,m]
    sigmoid = 1.0 / (1.0 + tf.exp( -1.0 * z ))
    tf.identity(sigmoid, "sigmoid")
    
    a = sigmoid
    tf.identity(a, "a")
    
    # define the error_rate test statistic and a TensorBoard summary 
    # yhat is our estimate of y given our current model
    yhat = tf.cast(a > 0.5, a.dtype)
    tf.identity(yhat, "yhat")
    
    match = tf.cast( tf.equal(yhat, y), yhat.dtype ) 
    error_rate = 1.0 - tf.reduce_mean( match, axis=1 )
    tf.identity(error_rate, "error_rate")
    error_rate_summary = tf.summary.scalar('Error_rate', error_rate[0])

In [9]:
if DEBUG: # test eq. (1)
    with tf.Session() as sess:
        init = tf.global_variables_initializer()
        init.run() # actual init of variable    
        result = z.eval( feed_dict={X:X_train , y:y_train} )
        
    assert ( result.shape == (1,m) )
        
    def debugExpectedZ():
        return  np.array( [[ 4.,  8., 12., 16., 20., 24., 28.]] )
    
    assert np.array_equal( result, debugExpectedZ() )

In [10]:
lrTest.debugZ(m, z, {X:X_train, y:y_train}, DEBUG)

In [11]:
if DEBUG: # test eq. (2)
    with tf.Session() as sess:
        init = tf.global_variables_initializer()
        init.run() # actual init of variable    
        result = a.eval( feed_dict={X:X_train , y:y_train} )
        
    assert (result.shape == (1,m) )

    def debugExpectedSigmoid():
        zz = debugExpectedZ()
        expected = 1.0 / ( 1.0 + np.exp(-1.0 * zz) )
        return expected
        
    assert np.array_equal( result, debugExpectedSigmoid() )

In [12]:
if DEBUG: # test error_rate
    with tf.Session() as sess:
        init = tf.global_variables_initializer()
        init.run() # actual init of variable    
        #result = error_rate.eval( feed_dict={X:X_train , y:y_train} )
        fetchResults = {
            "yhat":yhat,
            "match":match,
            "error_rate":error_rate
        }
        
        results = sess.run(fetchResults, 
                          feed_dict={X:X_train , y:y_train} )
        aa = a.eval(feed_dict={X:X_train , y:y_train})
        expected = 1 - np.sum((aa > 0.5) == y_train) / m
        assert results['error_rate'] == expected

## Evaluate Model
Create a graph to measure how well our preidiction match our lables

### Loss Equation
$$ 
L(a ,y)\: =\: -\,(\: ylog(a)\: +\: (1-y)log(1-a )\: ) \tag{3}
$$

### Cost Equations

$$ 
J(W,b)\: =\: 1/m\, \sum _{ i=1 }^{ m }{ L(a ^{ (i) } } ,{ y }^{ (i) }) \tag{4}
$$

In [13]:
with tf.name_scope("Cost"):
    # define loss function. Shape will be [1,m]

    # use member wise multiplication
    propY = tf.multiply( y, tf.log(a) )
    propNotY = tf.multiply( (1.0 - y), tf.log(1.0 - a) )
    loss = - ( propY + propNotY )
    tf.identity(loss, "loss")
    
    # define cost. i.e. average loss. Shape will be a real number
    # and a TensorBoard summary 

    cost = 1/m * tf.reduce_sum( loss )
    tf.identity(cost, "cost")
    cost_summary = tf.summary.scalar('Cost', cost)

In [14]:
if DEBUG:
    # test eq. (3)
    with tf.Session() as sess:
        init = tf.global_variables_initializer()
        init.run() # actual init of variable   
        result = loss.eval( feed_dict={X:X_train , y:y_train} )
        
    assert (result.shape == (1,m) )
        
    def debugExpectedLoss():
        aa = debugExpectedSigmoid()
        prob = y_train * np.log( aa )
        probNot = (1.0 - y_train) * np.log( 1.0 - aa )
        expected = -1.0 * ( prob + probNot )
        return expected
        
    expected = debugExpectedLoss()
    assert np.array_equal( result, expected )

    # test eq. (4)
    with tf.Session() as sess:
        init = tf.global_variables_initializer()
        init.run() # actual init of variable   
        result = cost.eval( feed_dict={X:X_train , y:y_train} )
    
    def debugCost():
        ll = debugExpectedLoss()
        expected = 1.0/m * np.sum(ll, axis=1)
        return expected
        
    r = np.round( result, decimals=6 )
    d = np.round( debugCost(), decimals=6 )
    assert (r == d)

## Backward propagation

### Partial derivatives of cost function with respect to weights

$$ \frac{\partial J(w,b)}{\partial w} = \frac{1}{m}X(A-Y)^T\tag{7}$$

### Partial derivatives of cost function with respect to bias
$$ \frac{\partial J(w,b)}{\partial b} = \frac{1}{m} \sum_{i=1}^m (a^{(i)}-y^{(i)})\tag{8}$$

In [15]:
with tf.name_scope("back_prop"):
    # Shape will be (n,1)
    dz = a - y
    tf.identity(dz, name="dz")
    
    dw = 1.0 / m * tf.matmul(X, tf.transpose(dz))
    tf.identity(dw, name="dw")

    # db is a scalar
    db = 1.0 / m * tf.reduce_sum( dz )
    tf.identity(db, name="db")

    learning_rate = 0.001
    update_w = tf.assign(w, w - learning_rate * dw, name="update_w")
    update_b = tf.assign(b, b - learning_rate * db, name="update_b")
    

In [16]:
if DEBUG: 
    with tf.name_scope("debug_gradient"):
        # test eq. (7)
        debug_reset_w = tf.assign( w, np.ones(( n, 1 )) )
        epsilon = 0.0001
        batch = {X:X_train, y:y_train}

        def debugGradientCheck():
            """uses definittion of derivative to compute a double side
            estimate of cost to check gradident"""

            with tf.Session() as sess:
                init = tf.global_variables_initializer()
                init.run()
                # get the partial derivate as calculated by our 
                # computation graph
                dwResult = dw.eval( feed_dict=batch )

            def debugEstimateCost(rowIdx):
                default = 1.
                posAdj = (default + epsilon/2.0)
                negAdj = (default + -1. * epsilon/2.0)
                if rowIdx == 0:
                    plusEps  = np.array( [[posAdj], [default]] )
                    minusEps = np.array( [[negAdj], [default]] )
                else:
                    plusEps  = np.array( [[default], [posAdj]] )
                    minusEps = np.array( [[default], [negAdj]] )

                def debugCost(adj):
                    with tf.Session() as sess:
                        init = tf.global_variables_initializer()
                        init.run() 
                        # tweak the values of w such that they will be 
                        # shared by the cost caluclation. We can use eval
                        # to share variables
                        fetchResults = [tf.assign(w,adj), cost]
                        _w, new_cost = sess.run(fetchResults,
                                                feed_dict=batch)
                        return new_cost

                upper_cost = debugCost( plusEps )
                lower_cost = debugCost( minusEps )

                estimate = (upper_cost - lower_cost) / epsilon
                return estimate

            g1 = debugEstimateCost(0)
            g2 = debugEstimateCost(1)
            estimated_gradients = np.array( [[g1], [g2]] )
            return [dwResult, estimated_gradients]


        dwResult, estimate = debugGradientCheck()
        rr = np.round(dwResult, decimals=7)
        gr = np.round(estimate, decimals=7)
        assert (np.array_equal(rr, gr))

        # as an additional check
        # Use tensor flow Automatic Differentiation to test gradient
        # Computing the gradient of cost with respect to W and b  
    with tf.name_scope("debug_gradient"):
        with tf.Session() as sess:
            init = tf.global_variables_initializer()
            init.run()        

            grad_w, grad_b = tf.gradients(xs=[w, b], ys=cost)
            gradWResult = grad_w.eval(feed_dict={X:X_train, y:y_train})

            # notice auto diff has greater precision than 2 sided estimate 
            rr = np.round(dwResult, decimals=11)
            gwr = np.round(gradWResult, decimals=11)
            assert (np.array_equal(rr, gwr))

In [17]:
if DEBUG: # test eq. (8)
    with tf.Session() as sess:
        init = tf.global_variables_initializer()
        init.run() # actual init of variable  
        batch = {X:X_train, y:y_train}
        result = db.eval( feed_dict=batch )
        
        # Use tensor flow Automatic Differentiation to test gradient
        # Computing the gradient of cost with respect to W and b
        grad_w, grad_b = tf.gradients(xs=[w, b], ys=cost)
        gBResult = grad_b.eval(feed_dict=batch)
        

        # notice greater precision than 2 sided estimate test
        rr = np.round(result, decimals=11)
        gbr = np.round(gBResult, decimals=11)
        assert (np.array_equal(rr, gbr))        

# Execute graph

In [18]:
def fetchBatch(X, y, batchIndex, batchSize ):
    start = batchIndex * batchSize
    end = start + batchSize
    xBatch = X[:,start:end]
    yBatch = y[:,start:end] 
    return xBatch, yBatch

if DEBUG:
    with tf.Session() as sess, tf.name_scope("train"):
        init = tf.global_variables_initializer()
        init.run() # actual init of variable   
        
        def testFetchBatch( batchIndex, batchSize, debug=False ):
            Xb, yb = fetchBatch(X_train, y_train, batchIndex,
                                batchSize )
            return Xb, yb

        Xb, yb = testFetchBatch( batchIndex=0, batchSize=2)
        assert np.array_equal( Xb, [[1., 3.], [2., 4.]] )
        assert np.array_equal( yb, [[0., 0.]] )

        Xb, yb = testFetchBatch( batchIndex=1, batchSize=2)
        assert np.array_equal( Xb, [[5., 7.], [6., 8.]] )
        assert np.array_equal( yb, [[0., 1.]] )

        # there are 4 patch, the index of last batch is 3 an only 
        # has 1 row
        Xb, yb = testFetchBatch( batchIndex=3, batchSize=2)
        assert np.array_equal( Xb, [[13.], [14.]] )
        assert np.array_equal( yb, [[1.]])


## Train Model

In [19]:
%%time
from datetime import datetime

# easy of use combine all the summaries 
merged_summary = tf.summary.merge_all()

init = tf.global_variables_initializer()

# set up logging so we can use TensorBoard to analyze results
now = datetime.utcnow().strftime("%Y_%m_%d_%H:%M:%S")
root_logdir = "tf_logs"
logdir = "{}/run-{}/".format(root_logdir, now)
    
# it appears that stats are collected for each mini batch
# how ever they are only written to disk when summary_writer.add()
# is executed.
summary_writer = tf.summary.FileWriter(logdir)
summary_writer.add_graph( tf.get_default_graph() )

with tf.Session() as sess:
    init.run() # actual init of variable
    previousCost = 0.
    for epoch in range( epochs ):
        totalCost = 0.0
        numBatches = int( np.ceil(m / batch_size) )
        for i in range( numBatches):   
            if i % log_frequence == 0:
                stat_data = { X:X_train, y:y_train }
                step = epoch * numBatches + i
                log_entry = sess.run(merged_summary, 
                                     feed_dict=stat_data)
                summary_writer.add_summary(log_entry, step)
                
            # train using next mini batch
            xBatch, yBatch = fetchBatch( X_train, y_train,
                                        batchIndex=i,
                                        batchSize=batch_size )
            
            data = { X:xBatch, y:yBatch}
            fetchResults = {
                        "cost":cost,
                        "error_rate":error_rate,
                        # the update ops are the root of our graph
                        "update_w":update_w,
                        "update_b":update_b
            }
                
            results = sess.run(fetchResults, feed_dict=data)
            totalCost += results["cost"]
                    
        # we expect the change to be negative if our model 
        # is improving
        change = totalCost - previousCost 
        previousCost = totalCost
        
        if ((epoch % log_frequence) == 0):             
            data = { X:X_train, y:y_train}
            answer = {"error_rate":error_rate}
            
            totalResults = sess.run(answer, feed_dict=data)
            fmt = "epoch:{:>4} totalCost:{:,.8f} change:{:,.8f}" + \
                    " error rate:{:,.5f}"
            print(fmt.format(epoch, totalCost, change, 
                             totalResults["error_rate"][0]) )
        
    print("\nm:", m, " epochs:", epochs)
    print("final error_rate:", totalResults["error_rate"] )
    print("logdir:", logdir)

# close the log file
summary_writer.close()
    
if DEBUG:    
    msg = "check epochs == 5000, learning_rate = 0.001"
    assert np.isclose(totalResults["error_rate"], 0.28571429),msg

epoch:   0 totalCost:0.56703763 change:0.56703763 error rate:0.06700
epoch:  20 totalCost:0.15448761 change:-0.00292511 error rate:0.03700
epoch:  40 totalCost:0.11653076 change:-0.00135690 error rate:0.03300
epoch:  60 totalCost:0.09495562 change:-0.00088699 error rate:0.03200
epoch:  80 totalCost:0.07996599 change:-0.00064538 error rate:0.02800

m: 1000  epochs: 100
final error_rate: [0.028]
logdir: tf_logs/run-2018_01_30_01:51:55/
CPU times: user 2min 27s, sys: 48.6 s, total: 3min 15s
Wall time: 3min 15s
